name = "FOSScraft"
author = "SpaceGameDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1c90d10d87025f80776758684a004aeacff2dadf47a724b0434e72448a70167"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
